// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// make_niche_logpost_xptr
SEXP make_niche_logpost_xptr(Rcpp::NumericMatrix occ, Rcpp::IntegerVector occ_start, Rcpp::IntegerVector N_occ, Rcpp::NumericMatrix env_m, Rcpp::IntegerVector m_start, Rcpp::IntegerVector N_m, Rcpp::NumericMatrix C, Rcpp::NumericVector mu_anc_prior, Rcpp::NumericVector mu_anc_sigma, double z_rho_anc_prior, double z_rho_anc_sigma, double rate_mu_scale, double rate_ls_scale, double rate_rho_scale, std::string model, double rho_cap, double sigma_floor, double jitter, std::string grad, Rcpp::NumericVector gradstep);
RcppExport SEXP _arfun_make_niche_logpost_xptr(SEXP occSEXP, SEXP occ_startSEXP, SEXP N_occSEXP, SEXP env_mSEXP, SEXP m_startSEXP, SEXP N_mSEXP, SEXP CSEXP, SEXP mu_anc_priorSEXP, SEXP mu_anc_sigmaSEXP, SEXP z_rho_anc_priorSEXP, SEXP z_rho_anc_sigmaSEXP, SEXP rate_mu_scaleSEXP, SEXP rate_ls_scaleSEXP, SEXP rate_rho_scaleSEXP, SEXP modelSEXP, SEXP rho_capSEXP, SEXP sigma_floorSEXP, SEXP jitterSEXP, SEXP gradSEXP, SEXP gradstepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type occ(occSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type occ_start(occ_startSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type N_occ(N_occSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type env_m(env_mSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type m_start(m_startSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type N_m(N_mSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type C(CSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu_anc_prior(mu_anc_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu_anc_sigma(mu_anc_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type z_rho_anc_prior(z_rho_anc_priorSEXP);
    Rcpp::traits::input_parameter< double >::type z_rho_anc_sigma(z_rho_anc_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type rate_mu_scale(rate_mu_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type rate_ls_scale(rate_ls_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type rate_rho_scale(rate_rho_scaleSEXP);
    Rcpp::traits::input_parameter< std::string >::type model(modelSEXP);
    Rcpp::traits::input_parameter< double >::type rho_cap(rho_capSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_floor(sigma_floorSEXP);
    Rcpp::traits::input_parameter< double >::type jitter(jitterSEXP);
    Rcpp::traits::input_parameter< std::string >::type grad(gradSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gradstep(gradstepSEXP);
    rcpp_result_gen = Rcpp::wrap(make_niche_logpost_xptr(occ, occ_start, N_occ, env_m, m_start, N_m, C, mu_anc_prior, mu_anc_sigma, z_rho_anc_prior, z_rho_anc_sigma, rate_mu_scale, rate_ls_scale, rate_rho_scale, model, rho_cap, sigma_floor, jitter, grad, gradstep));
    return rcpp_result_gen;
END_RCPP
}
// xptr_niche_logpost_eval
double xptr_niche_logpost_eval(SEXP xptr, Rcpp::NumericVector theta);
RcppExport SEXP _arfun_xptr_niche_logpost_eval(SEXP xptrSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xptr(xptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(xptr_niche_logpost_eval(xptr, theta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_arfun_make_niche_logpost_xptr", (DL_FUNC) &_arfun_make_niche_logpost_xptr, 20},
    {"_arfun_xptr_niche_logpost_eval", (DL_FUNC) &_arfun_xptr_niche_logpost_eval, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_arfun(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
