# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_niche_logpost_xptr <- function(occ, occ_start, N_occ, env_m, m_start, N_m, C, mu_anc_prior, mu_anc_sigma, z_rho_anc_prior, z_rho_anc_sigma, rate_mu_scale, rate_ls_scale, rate_rho_scale, model = "ctr", rho_cap = 0.98, sigma_floor = 0.02, jitter = 1e-9, grad = "central", gradstep = as.numeric( c(1e-6, 1e-8))) {
    .Call(`_arfun_make_niche_logpost_xptr`, occ, occ_start, N_occ, env_m, m_start, N_m, C, mu_anc_prior, mu_anc_sigma, z_rho_anc_prior, z_rho_anc_sigma, rate_mu_scale, rate_ls_scale, rate_rho_scale, model, rho_cap, sigma_floor, jitter, grad, gradstep)
}

xptr_niche_logpost_eval <- function(xptr, theta) {
    .Call(`_arfun_xptr_niche_logpost_eval`, xptr, theta)
}

